// CDK port of ../template.yaml, resource for resource. Read that file's comments for
// the decisions; this file only records where the CDK shape differs from the SAM one.
//
// Differences worth knowing:
// - Parameters became construct props (set from cdk.json context and ../.env). CDK apps
//   resolve configuration at synth time rather than with CloudFormation parameters.
// - Bundling: NodejsFunction runs esbuild with the same flags as the SAM esbuild metadata.
//   The Python function is a plain asset copy, as the SAM makefile did.
// - CloudFront OAC to the Lambda Function URL: the L2 origin grants lambda:InvokeFunctionUrl;
//   lambda:InvokeFunction is added explicitly below because the URL answers 403 without it.
// - Only the active backend is wired to CloudFront. The SAM template granted CloudFront
//   permissions on both functions; here the inactive one keeps its URL but no CloudFront grant.

import * as path from "node:path";
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import * as s3 from "aws-cdk-lib/aws-s3";
import * as lambda from "aws-cdk-lib/aws-lambda";
import { NodejsFunction, OutputFormat } from "aws-cdk-lib/aws-lambda-nodejs";
import * as iam from "aws-cdk-lib/aws-iam";
import * as logs from "aws-cdk-lib/aws-logs";
import * as cloudfront from "aws-cdk-lib/aws-cloudfront";
import * as origins from "aws-cdk-lib/aws-cloudfront-origins";
import * as acm from "aws-cdk-lib/aws-certificatemanager";
import * as route53 from "aws-cdk-lib/aws-route53";
import * as targets from "aws-cdk-lib/aws-route53-targets";
import * as dynamodb from "aws-cdk-lib/aws-dynamodb";
import * as sns from "aws-cdk-lib/aws-sns";
import * as subscriptions from "aws-cdk-lib/aws-sns-subscriptions";
import * as cloudwatch from "aws-cdk-lib/aws-cloudwatch";
import * as cwactions from "aws-cdk-lib/aws-cloudwatch-actions";
import * as budgets from "aws-cdk-lib/aws-budgets";
import * as bedrock from "aws-cdk-lib/aws-bedrock";

export interface WellmarkDemoStackProps extends cdk.StackProps {
  domainName: string;
  /** ACM certificate covering domainName. Must be in us-east-1 (CloudFront constraint). */
  certificateArn: string;
  /** Route 53 hosted zone that owns the domain. */
  hostedZoneId: string;
  /** Bedrock model or inference profile id available in the stack region. */
  modelId: string;
  maxOutputTokens: string;
  /** Caps simultaneous chats, which caps Bedrock spend. */
  reservedConcurrency: number;
  /** Hard cap on estimated model spend per UTC day. Enforced in the Lambda before every turn. */
  dailyBudgetUsd: number;
  /** Assumed input price, USD per million tokens. Set above list price so the cap errs early. */
  priceInPerMtok: number;
  /** Assumed output price, USD per million tokens. */
  priceOutPerMtok: number;
  /** Per-visitor fairness limit so one script cannot spend the whole day's budget. */
  ipTurnsPerHour: number;
  /** Where budget and traffic alerts go. Empty disables the alerts. */
  notificationEmail?: string;
  /** Which chat Lambda CloudFront routes /api/* to. Both are deployed; both cost nothing idle. */
  backend: "typescript" | "python";
}

const REPO_ROOT = path.resolve(__dirname, "../..");

export class WellmarkDemoStack extends cdk.Stack {
  constructor(scope: Construct, id: string, props: WellmarkDemoStackProps) {
    super(scope, id, props);

    if (!/^arn:aws:acm:us-east-1:/.test(props.certificateArn)) {
      throw new Error(`CloudFront certificates must live in us-east-1, got ${props.certificateArn}`);
    }

    // ---- Static site bucket (private; CloudFront reads it through OAC) ----
    const siteBucket = new s3.Bucket(this, "SiteBucket", {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      removalPolicy: cdk.RemovalPolicy.DESTROY, // demo content, regenerated by scripts/build-site.mjs
      autoDeleteObjects: false,
    });

    // ---- Guardrail (see template.yaml for the reasoning; DRAFT is the working version) ----
    const blockedMessage = "I can't help with that here. If it's about symptoms or treatment, please call the 24/7 nurse line at 1-800-555-0142, or 911 in an emergency. I can help with coverage, claims and your plan.";
    const guardrail = new bedrock.CfnGuardrail(this, "Guardrail", {
      name: `${this.stackName}-guardrail`,
      description: "Denies medical advice, common abuse categories and prompt attacks; masks financial and government identifiers.",
      blockedInputMessaging: blockedMessage,
      blockedOutputsMessaging: blockedMessage,
      topicPolicyConfig: { topicsConfig: [{
        name: "MedicalAdvice", type: "DENY",
        definition: "Diagnosing conditions, assessing symptoms, or advising for or against a treatment, drug, dose or procedure for a person's health. Asking whether care is covered is not this topic.",
        examples: [
          "I've had chest pain for three days, what should I take for it?",
          "Is 800mg of ibuprofen safe with my blood pressure medication?",
          "Do these symptoms sound like strep throat?",
          "Should I get the MRI or just try rest first?",
          "Which is better for my back, physical therapy or a steroid injection?",
        ],
      }] },
      contentPolicyConfig: { filtersConfig: [
        ...["HATE", "INSULTS", "SEXUAL", "VIOLENCE", "MISCONDUCT"].map((type) => ({ type, inputStrength: "HIGH", outputStrength: "HIGH" })),
        { type: "PROMPT_ATTACK", inputStrength: "HIGH", outputStrength: "NONE" },
      ] },
      // Only identifiers that never legitimately appear in a health-plan answer; names, addresses,
      // phones and emails are the demo's own synthetic data.
      sensitiveInformationPolicyConfig: { piiEntitiesConfig: [
        "US_SOCIAL_SECURITY_NUMBER", "CREDIT_DEBIT_CARD_NUMBER", "CREDIT_DEBIT_CARD_CVV", "CREDIT_DEBIT_CARD_EXPIRY",
        "US_BANK_ACCOUNT_NUMBER", "US_BANK_ROUTING_NUMBER", "INTERNATIONAL_BANK_ACCOUNT_NUMBER", "US_PASSPORT_NUMBER",
        "DRIVER_ID", "PASSWORD", "PIN", "AWS_ACCESS_KEY", "AWS_SECRET_KEY",
      ].map((type) => ({ type, action: "ANONYMIZE" })) },
    });
    const guardrailAccess = new iam.PolicyStatement({ actions: ["bedrock:ApplyGuardrail"], resources: [guardrail.attrGuardrailArn] });

    // ---- Chat Lambdas ----
    const bedrockAccess = new iam.PolicyStatement({
      actions: ["bedrock:InvokeModel", "bedrock:InvokeModelWithResponseStream"],
      resources: [
        `arn:aws:bedrock:${this.region}:${this.account}:inference-profile/*`,
        "arn:aws:bedrock:*::foundation-model/anthropic.*",
      ],
    });
    // One item per UTC day holds estimated spend; per-visitor hourly counters expire via TTL.
    const usageTable = new dynamodb.Table(this, "UsageTable", {
      partitionKey: { name: "pk", type: dynamodb.AttributeType.STRING },
      billingMode: dynamodb.BillingMode.PAY_PER_REQUEST,
      timeToLiveAttribute: "ttl",
      removalPolicy: cdk.RemovalPolicy.DESTROY, // counters only; nothing worth keeping
    });
    const environment = {
      MODEL_ID: props.modelId,
      MAX_OUTPUT_TOKENS: props.maxOutputTokens,
      USAGE_TABLE: usageTable.tableName,
      DAILY_BUDGET_USD: String(props.dailyBudgetUsd),
      PRICE_IN_PER_MTOK: String(props.priceInPerMtok),
      PRICE_OUT_PER_MTOK: String(props.priceOutPerMtok),
      IP_TURNS_PER_HOUR: String(props.ipTurnsPerHour),
      GUARDRAIL_ID: guardrail.attrGuardrailId,
      GUARDRAIL_VERSION: "DRAFT",
    };
    const usageAccess = new iam.PolicyStatement({
      actions: ["dynamodb:UpdateItem", "dynamodb:GetItem"],
      resources: [usageTable.tableArn],
    });
    const common = {
      architecture: lambda.Architecture.ARM_64,
      memorySize: 512,
      timeout: cdk.Duration.seconds(90),
      reservedConcurrentExecutions: props.reservedConcurrency,
      environment,
    };

    const chatFunction = new NodejsFunction(this, "ChatFunction", {
      ...common,
      runtime: lambda.Runtime.NODEJS_22_X,
      entry: path.join(REPO_ROOT, "api/src/handler.ts"),
      handler: "handler",
      depsLockFilePath: path.join(REPO_ROOT, "api/package-lock.json"),
      logGroup: new logs.LogGroup(this, "ChatFunctionLogs", { retention: logs.RetentionDays.ONE_MONTH, removalPolicy: cdk.RemovalPolicy.DESTROY }),
      bundling: {
        minify: true,
        target: "es2022",
        format: OutputFormat.ESM,
        sourceMap: false,
        externalModules: ["@aws-sdk/*"],
        // ESM bundles have no `require`; some transitive deps still call it.
        banner: "import { createRequire } from 'module'; const require = createRequire(import.meta.url);",
      },
    });
    chatFunction.addToRolePolicy(bedrockAccess);
    chatFunction.addToRolePolicy(usageAccess);
    chatFunction.addToRolePolicy(guardrailAccess);
    const chatFunctionUrl = chatFunction.addFunctionUrl({
      authType: lambda.FunctionUrlAuthType.AWS_IAM,
      invokeMode: lambda.InvokeMode.RESPONSE_STREAM,
    });

    // Python twin. Buffered, not streamed: the managed Python runtime cannot stream a Function URL response.
    const chatFunctionPy = new lambda.Function(this, "ChatFunctionPy", {
      ...common,
      runtime: lambda.Runtime.PYTHON_3_12,
      handler: "handler.handler",
      code: lambda.Code.fromAsset(path.join(REPO_ROOT, "api-python"), {
        exclude: ["__pycache__", "**/__pycache__", ".venv", "scripts", "Makefile", "requirements.txt"],
      }),
      logGroup: new logs.LogGroup(this, "ChatFunctionPyLogs", { retention: logs.RetentionDays.ONE_MONTH, removalPolicy: cdk.RemovalPolicy.DESTROY }),
    });
    chatFunctionPy.addToRolePolicy(bedrockAccess);
    chatFunctionPy.addToRolePolicy(usageAccess);
    chatFunctionPy.addToRolePolicy(guardrailAccess);
    const chatFunctionPyUrl = chatFunctionPy.addFunctionUrl({
      authType: lambda.FunctionUrlAuthType.AWS_IAM,
      invokeMode: lambda.InvokeMode.BUFFERED,
    });

    const active = props.backend === "python"
      ? { fn: chatFunctionPy, url: chatFunctionPyUrl }
      : { fn: chatFunction, url: chatFunctionUrl };

    // ---- CloudFront ----
    const urlRewrite = new cloudfront.Function(this, "UrlRewriteFunction", {
      comment: "Map /claims to /claims.html and directory paths to index.html; stamp the viewer IP on /api/*",
      runtime: cloudfront.FunctionRuntime.JS_2_0,
      code: cloudfront.FunctionCode.fromInline(`function handler(event) {
  var request = event.request;
  var uri = request.uri;
  if (uri.indexOf('/api/') === 0) {
    // The per-visitor rate limit keys on this. event.viewer.ip is what CloudFront
    // saw on the TLS connection; setting it here overwrites anything the client sent.
    request.headers['x-viewer-ip'] = { value: event.viewer.ip };
    return request;
  }
  if (uri.endsWith('/')) { request.uri = uri + 'index.html'; return request; }
  var last = uri.substring(uri.lastIndexOf('/') + 1);
  if (last.indexOf('.') === -1) { request.uri = uri + '.html'; }
  return request;
}`),
    });

    const certificate = acm.Certificate.fromCertificateArn(this, "Certificate", props.certificateArn);

    const securityHeaders = new cloudfront.ResponseHeadersPolicy(this, "SecurityHeaders", {
      securityHeadersBehavior: {
        strictTransportSecurity: { accessControlMaxAge: cdk.Duration.days(365), includeSubdomains: false, preload: false, override: true },
        contentTypeOptions: { override: true },
        frameOptions: { frameOption: cloudfront.HeadersFrameOption.DENY, override: true },
        referrerPolicy: { referrerPolicy: cloudfront.HeadersReferrerPolicy.STRICT_ORIGIN_WHEN_CROSS_ORIGIN, override: true },
        contentSecurityPolicy: {
          override: true,
          contentSecurityPolicy: "default-src 'self'; script-src 'self'; style-src 'self'; font-src 'self'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'; base-uri 'self'; form-action 'self'; object-src 'none'",
        },
      },
      customHeadersBehavior: {
        customHeaders: [{ header: "Permissions-Policy", value: "camera=(), microphone=(), geolocation=(), payment=()", override: true }],
      },
    });

    // CloudFront standard logs. Legacy log delivery writes with ACLs, hence BucketOwnerPreferred.
    const logBucket = new s3.Bucket(this, "LogBucket", {
      objectOwnership: s3.ObjectOwnership.BUCKET_OWNER_PREFERRED,
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      enforceSSL: true,
      lifecycleRules: [{ id: "expire", expiration: cdk.Duration.days(30) }],
      removalPolicy: cdk.RemovalPolicy.DESTROY,
    });

    const distribution = new cloudfront.Distribution(this, "Distribution", {
      comment: props.domainName,
      domainNames: [props.domainName],
      certificate,
      minimumProtocolVersion: cloudfront.SecurityPolicyProtocol.TLS_V1_2_2021,
      sslSupportMethod: cloudfront.SSLMethod.SNI,
      httpVersion: cloudfront.HttpVersion.HTTP2_AND_3,
      enableIpv6: true,
      priceClass: cloudfront.PriceClass.PRICE_CLASS_100,
      defaultRootObject: "index.html",
      enableLogging: true,
      logBucket,
      logFilePrefix: "cloudfront/",
      logIncludesCookies: false,
      defaultBehavior: {
        origin: origins.S3BucketOrigin.withOriginAccessControl(siteBucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
        allowedMethods: cloudfront.AllowedMethods.ALLOW_GET_HEAD_OPTIONS,
        cachedMethods: cloudfront.CachedMethods.CACHE_GET_HEAD,
        compress: true,
        cachePolicy: cloudfront.CachePolicy.CACHING_OPTIMIZED,
        responseHeadersPolicy: securityHeaders,
        functionAssociations: [{ function: urlRewrite, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST }],
      },
      additionalBehaviors: {
        "/api/*": {
          origin: origins.FunctionUrlOrigin.withOriginAccessControl(active.url, {
            readTimeout: cdk.Duration.seconds(60),
          }),
          viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.HTTPS_ONLY,
          allowedMethods: cloudfront.AllowedMethods.ALLOW_ALL,
          cachedMethods: cloudfront.CachedMethods.CACHE_GET_HEAD,
          compress: false,
          cachePolicy: cloudfront.CachePolicy.CACHING_DISABLED,
          originRequestPolicy: cloudfront.OriginRequestPolicy.ALL_VIEWER_EXCEPT_HOST_HEADER,
          responseHeadersPolicy: securityHeaders,
          functionAssociations: [{ function: urlRewrite, eventType: cloudfront.FunctionEventType.VIEWER_REQUEST }],
        },
      },
      errorResponses: [
        { httpStatus: 403, responseHttpStatus: 404, responsePagePath: "/404.html", ttl: cdk.Duration.seconds(60) },
        { httpStatus: 404, responseHttpStatus: 404, responsePagePath: "/404.html", ttl: cdk.Duration.seconds(60) },
      ],
    });

    // CloudFront's OAC needs InvokeFunction as well as InvokeFunctionUrl (AWS docs, 2026).
    // The L2 origin above grants only InvokeFunctionUrl; without this one every signed request gets a 403.
    active.fn.addPermission("CloudFrontInvokeFunction", {
      action: "lambda:InvokeFunction",
      principal: new iam.ServicePrincipal("cloudfront.amazonaws.com"),
      sourceArn: `arn:aws:cloudfront::${this.account}:distribution/${distribution.distributionId}`,
    });

    // ---- Alerts (only when an email is configured) ----
    if (props.notificationEmail) {
      const topic = new sns.Topic(this, "AlertTopic");
      topic.addSubscription(new subscriptions.EmailSubscription(props.notificationEmail));
      const alarmAction = new cwactions.SnsAction(topic);

      // Second line of defence: independent of the in-Lambda counter.
      new cloudwatch.Alarm(this, "TrafficAlarm", {
        alarmDescription: `More than 150 chat invocations in an hour on ${props.domainName}`,
        metric: chatFunction.metricInvocations({ period: cdk.Duration.hours(1), statistic: "Sum" }),
        threshold: 150,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }).addAlarmAction(alarmAction);
      new cloudwatch.Alarm(this, "ErrorAlarm", {
        alarmDescription: `Chat Lambda errors on ${props.domainName}`,
        metric: chatFunction.metricErrors({ period: cdk.Duration.minutes(5), statistic: "Sum" }),
        threshold: 5,
        evaluationPeriods: 1,
        comparisonOperator: cloudwatch.ComparisonOperator.GREATER_THAN_THRESHOLD,
        treatMissingData: cloudwatch.TreatMissingData.NOT_BREACHING,
      }).addAlarmAction(alarmAction);

      // Billing-side backstop. Cost data lags up to a day, so the Lambda cap is the real limit.
      // Budgets has no L2 construct; this is the L1 with the same shape as the SAM resource.
      const subscribers = [{ subscriptionType: "EMAIL", address: props.notificationEmail }];
      new budgets.CfnBudget(this, "DailyBudget", {
        budget: {
          budgetName: `${this.stackName}-daily`,
          budgetType: "COST",
          timeUnit: "DAILY",
          budgetLimit: { amount: props.dailyBudgetUsd, unit: "USD" },
          costFilters: { TagKeyValue: [`aws:cloudformation:stack-name$${this.stackName}`] },
        },
        notificationsWithSubscribers: [
          { notification: { notificationType: "ACTUAL", comparisonOperator: "GREATER_THAN", threshold: 80, thresholdType: "PERCENTAGE" }, subscribers },
          { notification: { notificationType: "ACTUAL", comparisonOperator: "GREATER_THAN", threshold: 100, thresholdType: "PERCENTAGE" }, subscribers },
        ],
      });
    }

    // ---- DNS ----
    const zoneName = props.domainName.split(".").slice(-2).join(".");
    const zone = route53.HostedZone.fromHostedZoneAttributes(this, "Zone", { hostedZoneId: props.hostedZoneId, zoneName });
    const target = route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(distribution));
    new route53.ARecord(this, "DnsRecordA", { zone, recordName: props.domainName, target });
    new route53.AaaaRecord(this, "DnsRecordAAAA", { zone, recordName: props.domainName, target });

    // ---- Outputs (same keys as template.yaml so deploy.sh's describe-stacks queries keep working) ----
    new cdk.CfnOutput(this, "SiteUrl", { value: `https://${props.domainName}` });
    new cdk.CfnOutput(this, "SiteBucketName", { value: siteBucket.bucketName });
    new cdk.CfnOutput(this, "DistributionId", { value: distribution.distributionId });
    new cdk.CfnOutput(this, "ChatFunctionName", { value: chatFunction.functionName });
    new cdk.CfnOutput(this, "ChatFunctionUrl", { value: chatFunctionUrl.url });
    new cdk.CfnOutput(this, "ChatFunctionPyName", { value: chatFunctionPy.functionName });
    new cdk.CfnOutput(this, "ActiveBackend", { value: props.backend });
    new cdk.CfnOutput(this, "UsageTableName", { value: usageTable.tableName });
    new cdk.CfnOutput(this, "GuardrailId", { value: guardrail.attrGuardrailId });
  }
}
