// Page copy for samplepayer.tvlss.com. Tool tables come from api/src/agents at build time.

export const home = {
  h1: "Seven assistants for a health plan's front line.",
  lede: "Each one answers a member or an employer by reading the systems the plan already runs. Every demo is live: ask a question, then watch which systems it called and what came back.",
  meta: "Built by TVLSS on AWS serverless with Claude on Amazon Bedrock. Everyone and everything in these demos is fictional. Nothing you type is kept once the reply is sent; the conversation lives only in this browser tab.",
  how: "The site is static files on S3 behind CloudFront. Questions go to one Lambda function that runs the agent loop: it sends the conversation and the agent's tool list to Claude on Bedrock, executes the tools Claude asks for against a synthetic copy of each back-office system, and streams the answer and every tool call back to the browser as they happen. Adding a benefit system means adding one adapter and one tool description; the agent learns to use it from the description alone.",
  facts: [
    ["Where it runs", "One CloudFormation stack in us-east-2 (Ohio), the nearest region to Iowa. No servers, no containers, nothing idling."],
    ["Cost per conversation", "Fractions of a cent in Lambda and CloudFront; the model is the cost. A typical five-question conversation on Claude Sonnet is roughly 3 to 6 cents at Bedrock list prices."],
    ["Cost when idle", "$0. Every component is pay-per-request."],
    ["Time to add a system", "One adapter function plus a one-paragraph tool description. No retraining, no prompt rewrite; the benefits demo added four systems this way."],
    ["What a real deployment adds", "Member sign-in and a session token in front of the API, real adapters behind the same tool interface, an audit log of every tool call, and PHI handling in a HIPAA-eligible account with Bedrock's data-retention settings confirmed in writing."],
    ["Stack", "AWS SAM, S3, CloudFront, Lambda Function URLs, Amazon Bedrock Converse API. The agent runtime exists twice, in TypeScript on Node 22 (streaming, live on this site) and in Python 3.12 (deployed alongside; one stack parameter routes the site to it)."],
  ],
};

export const pages = [
  {
    id: "benefits", nav: "Benefits",
    h1: "One benefits assistant, five benefit systems",
    tagline: "The existing benefits chatbot answers medical plan questions. This one also reads dental, vision, pharmacy and spending accounts, each through its own adapter, and combines them in one answer.",
    job: "Extends the current benefits chatbot to more benefit systems.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "medical, dental, vision, pharmacy or your FSA",
    greeting: "Hi Dana. I can answer questions about your medical, dental, vision and pharmacy benefits and your FSA. What are you wondering about?",
    samples: ["What would a dental crown and new glasses cost me this year?", "Is Ozempic covered, and what would I pay?", "How much is left on my FSA and when does it expire?", "Which benefit systems can you see?", "What would a specialist visit and an MRI cost me right now?"],
    about: [
      "The original benefits chatbot has one source: the medical benefits core. Members ask about dental crowns, glasses and prescriptions too, and get sent to a phone number. This assistant carries five adapters. Ask about a crown and glasses in one breath and it reads the dental system and the vision vendor, then answers with both.",
      "Ask it which systems it can see and it lists them from a tool, not from memory. That matters: the list is the integration inventory, and it is always current.",
    ],
    real: ["An adapter per system: medical core, dental administrator, the vision vendor's API, the PBM's formulary API, and the spending account administrator. Each is a small function with a fixed input and output.", "Member identity from the session, not the prompt.", "A benefit-language glossary the plan controls, so the assistant uses the plan's own terms."],
  },
  {
    id: "claims", nav: "Claims",
    h1: "Claims, explained line by line",
    tagline: "Status, what the member owes and why, why a claim was denied, and how to appeal, with the appeal filed from the conversation once the member says yes.",
    job: "A claims assistant that reads adjudicated claims and files appeals.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "a claim, an EOB, a denial or an appeal",
    greeting: "Hi Dana. I can look up any claim for you, Marcus or Ava, explain what you owe and why, and help with a denial. Which claim?",
    samples: ["Why was my physical therapy claim denied?", "What do I owe on the knee MRI, and why?", "Is Marcus's ER claim still pending?", "Show me all of our claims since July", "File an appeal on the denied physical therapy claim"],
    about: [
      "Members do not ask 'what is my claim status'; they ask 'why do I owe $860'. The assistant walks the claim in the order the plan adjudicated it: allowed amount, then deductible, then coinsurance or copay, using the claim's own numbers. Denials come with the reason code in plain language, what would make the claim payable, and the appeal deadline.",
      "The appeal is a write. The assistant states exactly what it will file and waits for a yes before calling the tool. The ledger marks write calls in red so a reviewer can see every change an agent made.",
    ],
    real: ["Read access to the claims system and EOB documents, and a write path into the appeals workflow with the same intake fields the call center uses.", "Denial reason codes mapped to plain-language explanations the plan has approved.", "Every write tool call logged with the member's confirmation text attached."],
  },
  {
    id: "membership", nav: "Membership",
    h1: "Membership changes without a phone call",
    tagline: "Who is covered, eligibility on a date, address and phone updates, replacement ID cards and primary care provider changes, with the change shown before it is made.",
    job: "A membership assistant that handles eligibility and service requests.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "coverage, your address, an ID card or your PCP",
    greeting: "Hi Dana. I can tell you who's covered, confirm eligibility, update your contact details, send ID cards or change a primary care provider. What do you need?",
    samples: ["Who's covered on my plan?", "We moved to 812 Oakland Rd NE, Cedar Rapids 52402. Update our address.", "Send Ava a new ID card", "Is Marcus eligible for coverage on October 1?", "Change my PCP to someone taking new patients"],
    about: [
      "Most membership calls are service requests, not questions. The assistant reads the current record first so it can show the before and after, then asks for a yes before writing. An address change applies to the whole family, and it says so.",
      "The PCP change reaches into the provider directory to offer in-network options that accept new patients, then writes to membership. Two systems, one conversation.",
    ],
    real: ["Membership and eligibility APIs with an effective-dated write path.", "ID card fulfilment (print vendor and digital wallet) behind one request tool.", "Identity proofing for changes that affect mail delivery, and a change notification to the member's email on file."],
  },
  {
    id: "group", nav: "Group",
    h1: "Group administration for the HR director",
    tagline: "Enrollment by plan, invoices and their breakdown, the renewal proposal with alternatives, and employee adds and terminations. The user here is the employer's administrator, not a member.",
    job: "A group assistant for employer benefits administrators.",
    persona: "Renee Castillo · HR Director, Cedar Rapids Machine Works",
    placeholder: "enrollment, invoices, renewal or an employee change",
    greeting: "Hi Renee. I can help with Cedar Rapids Machine Works' enrollment, invoices, renewal and employee changes. What would you like to look at?",
    samples: ["What's our renewal looking like?", "How many employees are enrolled by plan?", "Do we have any unpaid invoices?", "Break down the September invoice", "Add new hire Jordan Petrakis, hired August 18, to the PPO, employee plus spouse"],
    about: [
      "A group administrator's questions are about counts, dollars and dates: participation, what the September invoice is made of, what the renewal costs and what the alternatives cost. The assistant answers with the numbers first and the drivers second.",
      "It also enforces a boundary the group system would: it can discuss enrollment and billing facts about an employee, never that employee's claims or health information.",
    ],
    real: ["Group administration and billing APIs, including the enrollment write path with effective-date rules.", "Renewal proposals fed from underwriting, with the alternatives the account manager has already approved.", "Administrator sign-in tied to the group, and broker access as a separate role."],
  },
  {
    id: "accumulations", nav: "Accumulations",
    h1: "Deductibles and out-of-pocket, with the math shown",
    tagline: "Where each person and the family stand against deductible and out-of-pocket maximum, what moved the numbers, and what an upcoming service is likely to cost.",
    job: "An accumulations assistant that explains balances and estimates cost share.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "your deductible, out-of-pocket max or a cost estimate",
    greeting: "Hi Dana. I can show where you and your family stand on the deductible and out-of-pocket maximum, what moved them, and estimate what a service would cost you. What would you like to know?",
    samples: ["How close is my family to the deductible?", "What would a $2,000 outpatient procedure cost me?", "What moved my deductible this year?", "Where are we against the out-of-pocket max?", "How many physical therapy visits have I used?"],
    about: [
      "Accumulator questions are the ones members get wrong most, because the embedded family rule and the difference between deductible and out-of-pocket are hard to hold in your head. The assistant always gives met, limit and remaining together, and shows the arithmetic for an estimate in two lines.",
      "The estimator is a tool, not the model doing math in its head: remaining deductible first, then coinsurance, capped by the out-of-pocket maximum. The model explains the result; the code computes it.",
    ],
    real: ["The accumulator service with per-member and family balances, and the claims history that feeds it.", "A cost estimator using contracted rates for the member's network, so the 'allowed amount' is looked up rather than typed in.", "Plan design read from the benefits core so the copay and coinsurance rules are never hard-coded."],
  },
  {
    id: "health-services", nav: "Health services",
    h1: "Prior authorization and care programs",
    tagline: "Whether a service needs approval and who submits it, where a pending authorization stands, care programs the member qualifies for, and the nurse line. Coverage answers only, never clinical ones.",
    job: "A health services assistant for prior auth, care programs and the nurse line.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "prior authorization, care programs or the nurse line",
    greeting: "Hi Dana. I can check whether a service needs prior authorization, look up pending approvals, and show care programs you qualify for. I don't give medical advice, but I can connect you with the nurse line any time.",
    samples: ["Does a sleep study need prior authorization?", "Is there a prior auth pending for Marcus?", "What care programs am I eligible for?", "Enroll me in the back and joint care program", "What's the nurse line number, and does telehealth cost anything?"],
    about: [
      "This is the demo with the sharpest guardrail. Members bring symptoms; the assistant answers the coverage question, points to the nurse line, and does not assess anything clinical. Try describing knee pain and asking about physical therapy.",
      "It also does something a chatbot rarely does: it notices. Dana has an MRI and physical therapy claims, so the back and joint care program, with no cost share, is flagged as something she is likely eligible for, and she can enroll from the conversation.",
    ],
    real: ["Utilization management APIs for authorization status and the plan's prior-auth rules by procedure code.", "Care management enrollment with the program vendor's intake fields.", "Clinical-content review of the guardrail prompt by the plan's medical and compliance teams, and a test set of symptom questions it must decline."],
  },
  {
    id: "provider-network", nav: "Provider network",
    h1: "Find care that's in network",
    tagline: "Search by specialty and what matters to the member, confirm a specific provider's network status and contract end date, compare in- and out-of-network cost, and report directory errors.",
    job: "A provider network assistant over the directory and contracts.",
    persona: "Dana Whitfield · member W20419873",
    placeholder: "a specialty, a provider, or in- vs out-of-network cost",
    greeting: "Hi Dana. I can find in-network providers near you, check whether a specific doctor is in network, and show what going out of network would cost. Who are you looking for?",
    samples: ["Find a dermatologist taking new patients", "Is Dr. Lindqvist still in network?", "Physical therapists near Cedar Rapids", "What would out-of-network physical therapy cost me versus in network?", "A female psychiatrist who does telehealth"],
    about: [
      "Directory search is a filter problem: specialty, distance, accepting new patients, telehealth, language, gender. The assistant turns a sentence into those filters and returns at most five, ordered by distance, and says how it ordered them. It never ranks clinicians on medical grounds.",
      "Network status reads the contracting system, not just the directory. Dr. Lindqvist's contract ends December 31, so the answer includes the date and the continuity-of-care letter members will get.",
    ],
    real: ["The provider directory API with real-time appointment availability where the practice exposes it.", "Contract effective and termination dates from network contracting, which is what makes 'in network today' trustworthy.", "The directory-correction workflow, which regulators already require the plan to run."],
  },
];
